In [2]:
import torch

In [3]:
import numpy as np

In [4]:
torch.__version__

'2.0.1+cu118'

In [5]:
arr = np.array([1, 2, 3, 4, 5])

In [6]:
print(arr)

[1 2 3 4 5]


In [7]:
arr.dtype

dtype('int64')

In [8]:
type(arr)

numpy.ndarray

In [9]:
torch.from_numpy(arr)

tensor([1, 2, 3, 4, 5])

In [10]:
x = torch.from_numpy(arr)

In [11]:
type(x)

torch.Tensor

In [13]:
x.dtype

torch.int64

In [14]:
torch.as_tensor(arr)

tensor([1, 2, 3, 4, 5])

In [15]:
arr2d = np.arange(0.0, 12.0)
arr2d = arr2d.reshape(4,3)

In [16]:
arr2d

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [17]:
x1 = torch.from_numpy(arr2d)

In [18]:
x1

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)

In [19]:
arr

array([1, 2, 3, 4, 5])

In [20]:
x

tensor([1, 2, 3, 4, 5])

In [22]:
arr[0] = 99

In [23]:
arr

array([99,  2,  3,  4,  5])

In [24]:
x

tensor([99,  2,  3,  4,  5])

In [25]:
arr1 = np.arange(0,10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
tensor1 = torch.tensor(arr1)
tensor1

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
arr1[0] = 99
arr1

array([99,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [29]:
tensor1

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
arr2 = np.array([1, 2, 3])
arr2.dtype

dtype('int64')

In [31]:
torch.tensor(arr2)

tensor([1, 2, 3])

In [32]:
torch.Tensor(arr2)

tensor([1., 2., 3.])

In [33]:
torch.FloatTensor(arr2)

tensor([1., 2., 3.])

In [34]:
torch.Tensor(arr2) == torch.FloatTensor(arr2)

tensor([True, True, True])

In [35]:
torch.empty(2, 2)

tensor([[ 6.6765e+01,  3.1769e-41],
        [-8.0849e-17,  4.3509e-41]])

In [36]:
torch.zeros(3, 4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [38]:
torch.zeros(2, 3, dtype = torch.int32)

tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

In [39]:
torch.ones(4, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [40]:
torch.arange(0, 20, 2)

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [41]:
torch.arange(0, 15, 1).reshape(3, 5)

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [44]:
torch.linspace(0,10, 20)

tensor([ 0.0000,  0.5263,  1.0526,  1.5789,  2.1053,  2.6316,  3.1579,  3.6842,
         4.2105,  4.7368,  5.2632,  5.7895,  6.3158,  6.8421,  7.3684,  7.8947,
         8.4211,  8.9474,  9.4737, 10.0000])

In [45]:
torch.tensor([3, 4, 5])

tensor([3, 4, 5])

In [46]:
torch2 = torch.tensor([6, 7, 8])
torch2

tensor([6, 7, 8])

In [48]:
torch2.dtype

torch.int64

In [49]:
torch2.type(torch.int32)

tensor([6, 7, 8], dtype=torch.int32)

In [51]:
torch.rand(1)

tensor([0.1628])

In [52]:
torch.rand(2, 3)

tensor([[0.8321, 0.7323, 0.0603],
        [0.0100, 0.2563, 0.2146]])

In [55]:
torch.randn(2, 3)

tensor([[ 0.0370,  0.7899, -1.0394],
        [ 0.8088, -0.5683, -0.7795]])

In [59]:
torch.randint(low = 0, high = 10, size = (2, 2))

tensor([[2, 7],
        [2, 3]])

In [60]:
x2 = torch.zeros(2, 5)
x2

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [61]:
torch.rand_like(x2)

tensor([[0.9670, 0.4438, 0.0220, 0.8643, 0.0096],
        [0.4985, 0.8989, 0.1397, 0.7340, 0.0742]])

In [62]:
torch.randn_like(x2)

tensor([[ 0.9435,  0.1133, -1.3782, -0.4676,  0.2749],
        [-1.2395, -0.0838,  0.5393, -0.3573,  1.4724]])

In [65]:
torch.randint_like(x2, low =0, high =100, dtype= torch.int64)

tensor([[19, 79, 41, 22, 73],
        [68, 20,  2, 83, 12]])

In [66]:
torch.manual_seed(42)
torch.rand(2, 3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [67]:
x3 = torch.arange(6).reshape(3, 2)
x3

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [68]:
x3[1,1]

tensor(3)

In [69]:
type(x3[1, 1])

torch.Tensor

In [70]:
x3[:, 1]

tensor([1, 3, 5])

In [71]:
x3[:, 1:]

tensor([[1],
        [3],
        [5]])

In [72]:
x4 = torch.arange(10)
x4

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
x4.view(2, 5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [74]:
x4

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
x4.reshape(2, 5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [76]:
x4

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
x4 = x4.reshape(2, 5)

In [79]:
x4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [82]:
x4.view(5, -1)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [83]:
x4.view(-1, 1)

tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [84]:
a = torch.tensor([1., 2., 3.])
b = torch.tensor([4., 5., 6.])

In [85]:
a + b

tensor([5., 7., 9.])

In [86]:
a - b

tensor([-3., -3., -3.])

In [87]:
a * b

tensor([ 4., 10., 18.])

In [88]:
a / b

tensor([0.2500, 0.4000, 0.5000])

In [89]:
torch.add(a, b)

tensor([5., 7., 9.])

In [90]:
a.mul(b)

tensor([ 4., 10., 18.])

In [91]:
a

tensor([1., 2., 3.])

In [92]:
a.mul_(b)

tensor([ 4., 10., 18.])

In [93]:
a

tensor([ 4., 10., 18.])

In [94]:
c = torch.tensor([1, 2, 3])
d = torch.tensor([4, 5, 6])

In [95]:
c

tensor([1, 2, 3])

In [96]:
d

tensor([4, 5, 6])

In [97]:
c.dot(d)

tensor(32)

In [102]:
c.cross(d)

tensor([-3,  6, -3])

In [98]:
e = torch.tensor([[0, 2, 4], [1, 3, 5]])
e

tensor([[0, 2, 4],
        [1, 3, 5]])

In [99]:
f = torch.tensor([[1, 2], [3, 4], [5, 6]])
f

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [101]:
torch.mm(e, f)

tensor([[26, 32],
        [35, 44]])

In [103]:
e @ f

tensor([[26, 32],
        [35, 44]])

In [108]:
g = torch.FloatTensor([1, 2, 3, 4])
g

tensor([1., 2., 3., 4.])

In [109]:
g.norm()

tensor(5.4772)

In [110]:
g.numel()

4