In [ ]:
import numpy as np

In [ ]:
mylist = [1,2,3]

In [ ]:
print(type(mylist))

<class 'list'>


In [ ]:
np.array(mylist)

array([1, 2, 3])

In [ ]:
type(mylist)

list

In [ ]:
arr = np.array(mylist)

In [ ]:
arr

array([1, 2, 3])

In [ ]:
list1 = [[1,2,3], [4,5,6],[7,8,9]]

In [ ]:
np.array(list1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
matrix = np.array(list1)

In [ ]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
matrix.shape

(3, 3)

In [ ]:
arr1 = np.arange(0,10)

In [ ]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr2 = np.arange(0,10,2)

In [ ]:
arr2

array([0, 2, 4, 6, 8])

In [ ]:
arr3 = np.zeros(5)

In [ ]:
arr3

array([0., 0., 0., 0., 0.])

In [ ]:
arr4 = np.ones(10)

In [ ]:
arr4

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
type(1.0)

float

In [ ]:
type(0.)

float

In [ ]:
matrix1 = np.zeros((4, 10))

In [ ]:
matrix1

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
matrix2 = np.ones((3,2))

In [ ]:
matrix2

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
matrix2 = np.ones((2, 3)) + 3

In [ ]:
matrix2

array([[4., 4., 4.],
       [4., 4., 4.]])

In [ ]:
arr5 = np.ones(3) * 99

In [ ]:
arr5

array([99., 99., 99.])

In [ ]:
arr6 = np.linspace(0, 10, 5)

In [ ]:
arr6

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
len(arr6)

5

In [ ]:
matrix3 = np.eye(4)

In [ ]:
matrix3

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.random.rand(1)

array([0.90640597])

In [ ]:
np.random.rand(4)

array([0.63259019, 0.97110271, 0.13972474, 0.5074215 ])

In [ ]:
np.random.rand(5, 5)

array([[0.37582159, 0.28827389, 0.90493579, 0.96696054, 0.05991182],
       [0.72882208, 0.7942431 , 0.86709475, 0.56466881, 0.24758761],
       [0.73244978, 0.40780771, 0.78755611, 0.78813378, 0.22184062],
       [0.53372813, 0.21486425, 0.8753141 , 0.00640222, 0.48148844],
       [0.68666876, 0.2703547 , 0.96788853, 0.4909901 , 0.36999321]])

In [ ]:
np.random.randn(10)

array([-1.38544632, -0.73094461, -0.73868605, -0.13777026,  1.24041719,
        0.2736415 ,  0.53181747, -2.27248771, -2.43772889,  0.66874424])

In [ ]:
np.random.randint(1, 100)

94

In [ ]:
np.random.randint(1, 50, 10)

array([33, 49, 10, 42,  6, 14, 35, 34, 31, 11])

In [ ]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [ ]:
num = np.arange(25)

In [ ]:
num

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
num.shape

(25,)

In [ ]:
num.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
num1 = np.random.randint(0, 50, 10)

In [ ]:
num1

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

In [ ]:
num1.max()

39

In [ ]:
num1.min()

2

In [ ]:
num1.argmax()

7

In [ ]:
num1.argmin()

9

In [ ]:
num1.dtype

dtype('int64')

In [ ]:
num1.sort()
num1

array([ 2, 10, 10, 18, 22, 23, 23, 35, 38, 39])

In [ ]:
num1[3]

18

In [ ]:
num1[0:5]

array([ 2, 10, 10, 18, 22])

In [ ]:
num1[2:]

array([10, 18, 22, 23, 23, 35, 38, 39])

In [ ]:
num1

array([ 2, 10, 10, 18, 22, 23, 23, 35, 38, 39])

In [ ]:
num1 + 10

array([12, 20, 20, 28, 32, 33, 33, 45, 48, 49])

In [ ]:
num1 / 2

array([ 1. ,  5. ,  5. ,  9. , 11. , 11.5, 11.5, 17.5, 19. , 19.5])

In [ ]:
num1 ** 2

array([   4,  100,  100,  324,  484,  529,  529, 1225, 1444, 1521])

In [ ]:
num1

array([ 2, 10, 10, 18, 22, 23, 23, 35, 38, 39])

In [ ]:
slice_of_num1 = num1[0: 5]

In [ ]:
slice_of_num1

array([ 2, 10, 10, 18, 22])

In [ ]:
slice_of_num1[:] = 99

In [ ]:
slice_of_num1

array([99, 99, 99, 99, 99])

In [ ]:
num1

array([99, 99, 99, 99, 99, 23, 23, 35, 38, 39])

In [ ]:
num2 = np.arange(0, 10)

In [ ]:
num2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
num2_copy = num2.copy()

In [ ]:
num2_copy

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
num2_copy[:] = 121

In [ ]:
num2_copy

array([121, 121, 121, 121, 121, 121, 121, 121, 121, 121])

In [ ]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

In [ ]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
arr_2d.shape

(3, 3)

In [ ]:
arr_2d[1]

array([20, 25, 30])

In [ ]:
arr_2d[1][1]

25

In [ ]:
arr_2d[1,1]

25

In [ ]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [ ]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [104]:
array = np.arange(1, 11)

In [105]:
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [106]:
array > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [108]:
bool_array = array > 3

In [109]:
bool_array

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [110]:
array[bool_array]

array([ 4,  5,  6,  7,  8,  9, 10])

In [111]:
array[array>5]

array([ 6,  7,  8,  9, 10])

In [112]:
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [113]:
(array + 2) / 100

array([0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11, 0.12])

In [114]:
array + array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [115]:
array / array

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [116]:
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [117]:
np.sqrt(array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [119]:
np.log(array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [120]:
np.sin(array)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [121]:
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [122]:
array.sum()

55

In [123]:
array.mean()

5.5

In [124]:
array_2d = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [125]:
array_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [126]:
array_2d.sum()

45

In [128]:
array_2d.sum(axis=0)

array([12, 15, 18])

In [129]:
array_2d.sum(axis=1)

array([ 6, 15, 24])